version: '3'
services:
  proxy:
    networks:
        public:
        internal_control:
        internal_data:
  target:
    networks:
        public:
        internal_control:
        internal_data:
networks:
  internal_control:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: ${INT_CONTROL_SUBNET}
  internal_data:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: ${INT_DATA_SUBNET}


