version: '3'
services:
  dfcproxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ROLE=proxy
      - DFCPRIMARYPROXY=${DFCPRIMARYPROXY}
    env_file:
      - aws.env
    volumes:
      - ../dfc:/go/src/github.com/NVIDIA/dfcpub/dfc
  dfctarget:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROLE=target
    env_file:
      - aws.env
    volumes:
      - ../dfc:/go/src/github.com/NVIDIA/dfcpub/dfc
