apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfctarget
spec:
  selector:
    matchLabels:
      app: dfctarget-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dfctarget-app
    spec:
      hostNetwork: true
      containers:
      - name: dfctarget
        image: quay.io/nvidia/dfc
        imagePullPolicy: Always
        env:
         - name: ROLE
           value: "target"
        volumeMounts:
         - name: dfc-config
           mountPath: /etc/dfc/dfc.json
           subPath: dfc.json
         - name: collectd-config
           mountPath: /etc/collectd/collectd.conf
           subPath: collectd.conf
         - name: statsd-config
           mountPath: /opt/statsd/statsd.conf
           subPath: statsd.conf
         - name: aws-credentials
           mountPath: /root/.aws/
         - name: dfc-fs
           mountPath: /usr/nvidia/data
         - name: dfc-log
           mountPath: /tmp/
        ports:
          - containerPort: 8081
      nodeSelector:
          nodename: target
      volumes:
        - name: dfc-config
          configMap:
            name: dfc-config
        - name: collectd-config
          configMap:
            name: collectd-config
        - name: statsd-config
          configMap:
            name: statsd-config
        - name: aws-credentials
          secret:
            secretName: aws-credentials
        - name: dfc-fs
          hostPath:
            path: /dfc
            type: Directory
        - name: dfc-log
          hostPath:
            path: /tmp
            type: Directory
