---
- hosts: all
  gather_facts: no
  become: true
  vars:
    cluster: cluster3
  tasks:
    - fetch:
        src: /home/ubuntu/dfc/src/github.com/NVIDIA/dfcpub/bench/dfcloader/screenlog.0
        dest: "{{ cluster }}/logs/{{ inventory_hostname }}/"
        flat: yes
...

